---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  #vars_files:
  #  - ../../defaults/main.yml
  #vars:


  tasks:
    - name: "Include ansible_role_wireguard_serve"
      include_role:
        name: "ansible_role_wireguard_client"

  #roles:
    #- role: habbis.ansible_role_wireguard_client_server
